remote_theme: juicy-web/jekyll-theme-html5up-phantom
title: "Juicy Web"
author: "Juicy Web"
markdown: kramdown
highlighter: rouge
head_content: '<script type="text/javascript">window.cookieconsent_options={"message":"This website uses cookies to ensure you get the best experience on our website","dismiss":"Got it!","learnMore":"More info","link":"https://www.marvnet.de/privacy.htm","theme":"dark-bottom"};</script><script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/1.0.10/cookieconsent.min.js"></script>'
